# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\projects\master\CS553\dev\assembler\ui\ui_assembler_main.ui'
#
# Created: Mon Nov  1 17:05:48 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Assembler(object):
    def setupUi(self, Assembler):
        Assembler.setObjectName("Assembler")
        Assembler.resize(1108, 892)
        self.centralwidget = QtGui.QWidget(Assembler)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabPages = QtGui.QTableView(self.groupBox)
        self.tabPages.setObjectName("tabPages")
        self.verticalLayout.addWidget(self.tabPages)
        self.splitter = QtGui.QSplitter(self.groupBox)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.btnDownVersion = QtGui.QPushButton(self.splitter)
        self.btnDownVersion.setObjectName("btnDownVersion")
        self.btnUpVersion = QtGui.QPushButton(self.splitter)
        self.btnUpVersion.setObjectName("btnUpVersion")
        self.verticalLayout.addWidget(self.splitter)
        self.btnReload = QtGui.QPushButton(self.groupBox)
        self.btnReload.setObjectName("btnReload")
        self.verticalLayout.addWidget(self.btnReload)
        self.splitter_2 = QtGui.QSplitter(self.groupBox)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.chbSelected = QtGui.QCheckBox(self.splitter_2)
        self.chbSelected.setMaximumSize(QtCore.QSize(100, 16777215))
        self.chbSelected.setChecked(True)
        self.chbSelected.setObjectName("chbSelected")
        self.btnSendLatest = QtGui.QPushButton(self.splitter_2)
        self.btnSendLatest.setObjectName("btnSendLatest")
        self.verticalLayout.addWidget(self.splitter_2)
        self.splitter_3 = QtGui.QSplitter(self.groupBox)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.linPDFVersion = QtGui.QLineEdit(self.splitter_3)
        self.linPDFVersion.setMaximumSize(QtCore.QSize(100, 16777215))
        self.linPDFVersion.setAlignment(QtCore.Qt.AlignCenter)
        self.linPDFVersion.setObjectName("linPDFVersion")
        self.btnGeneratePDF = QtGui.QPushButton(self.splitter_3)
        self.btnGeneratePDF.setObjectName("btnGeneratePDF")
        self.verticalLayout.addWidget(self.splitter_3)
        self.horizontalLayout.addWidget(self.groupBox)
        self.grp_images = QtGui.QGroupBox(self.centralwidget)
        self.grp_images.setObjectName("grp_images")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.grp_images)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labPage = QtGui.QLabel(self.grp_images)
        self.labPage.setObjectName("labPage")
        self.verticalLayout_2.addWidget(self.labPage)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.grp_images)
        Assembler.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Assembler)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1108, 21))
        self.menubar.setObjectName("menubar")
        Assembler.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Assembler)
        self.statusbar.setObjectName("statusbar")
        Assembler.setStatusBar(self.statusbar)

        self.retranslateUi(Assembler)
        QtCore.QMetaObject.connectSlotsByName(Assembler)

    def retranslateUi(self, Assembler):
        Assembler.setWindowTitle(QtGui.QApplication.translate("Assembler", "Book Assembler", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Assembler", "Pages", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDownVersion.setText(QtGui.QApplication.translate("Assembler", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUpVersion.setText(QtGui.QApplication.translate("Assembler", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReload.setText(QtGui.QApplication.translate("Assembler", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.chbSelected.setText(QtGui.QApplication.translate("Assembler", "SEL", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSendLatest.setText(QtGui.QApplication.translate("Assembler", "Send Latest Versions", None, QtGui.QApplication.UnicodeUTF8))
        self.btnGeneratePDF.setText(QtGui.QApplication.translate("Assembler", "Generate PDF file", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_images.setTitle(QtGui.QApplication.translate("Assembler", "Page Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.labPage.setText(QtGui.QApplication.translate("Assembler", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

